{"@t":"2021-02-15T17:47:39.8304619Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":212,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T17:52:43.8930904Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":196,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T17:57:47.9514986Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":212,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:02:52.0119952Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":196,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:07:56.0868918Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:13:00.1912117Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:18:04.2373901Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:23:08.2759583Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:28:12.3266334Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:33:16.3879555Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":171,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:38:20.4485994Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":171,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:43:24.5283419Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":171,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:48:28.6196793Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:53:32.6930290Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T18:58:36.7598137Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":32,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:03:40.8279900Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":32,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:08:44.9164472Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:13:48.9957929Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:18:53.0835175Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:23:57.1541929Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:29:01.2109330Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:34:05.2341399Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":190,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:39:09.2768002Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:44:13.3507681Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":190,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:49:17.4007427Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":36,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:54:21.4661526Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":118,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T19:59:25.5396478Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":175,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:04:29.6360691Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":190,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:09:33.7437510Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":175,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:14:37.8408916Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":175,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:19:41.9305084Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":175,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:24:45.9986388Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:29:50.0533418Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:34:54.1042887Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:39:58.1915935Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":139,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:45:02.2540469Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:50:06.3119239Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T20:55:10.3851200Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:00:14.4544099Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:05:18.5324393Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:10:22.6114811Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:15:26.7024152Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:20:30.7927579Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:25:34.8568561Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:30:38.8993590Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:35:42.9613101Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:40:47.0585693Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:45:51.1166205Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:50:55.2061182Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T21:55:59.2664732Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-15T22:01:03.3566831Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":202,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
