{"@t":"2021-02-14T17:42:33.8896845Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":138,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T17:47:37.9287780Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":138,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T17:52:41.9741441Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":196,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T17:57:46.0417321Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":188,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:02:50.0803228Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":188,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:07:54.1295252Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:12:58.2329268Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:18:02.2821747Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:23:06.3406830Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":152,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:28:10.3932198Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":144,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:33:14.4672119Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":144,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:38:18.5112463Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":141,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:43:22.5689542Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":141,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:48:26.6267942Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":134,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:53:30.6643871Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":164,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T18:58:34.7216895Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":164,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:03:38.7660252Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":137,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:08:42.8279088Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":164,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:13:46.9223686Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":164,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:18:51.0059120Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":180,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:23:55.0711568Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":188,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:28:59.1564588Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":188,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:34:03.2729221Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":136,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:39:07.3657916Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":133,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:44:11.4543756Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":136,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:49:15.5134366Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":136,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:54:19.6215024Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":133,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T19:59:23.7239921Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":133,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:04:27.8158954Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":133,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:09:31.8726036Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":133,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:14:35.9718169Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":141,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:19:40.0334541Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":142,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:24:44.1233694Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":152,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:29:48.1934275Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":193,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:34:52.2649590Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":193,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:39:56.3236397Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":193,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:45:00.3928697Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:50:04.4330311Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":193,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T20:55:08.4827349Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":193,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:00:12.5902296Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:05:16.6549335Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:10:20.7516463Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":66,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:15:24.8007431Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":198,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:20:28.8441766Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":124,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:25:32.9292104Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":158,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:30:37.0029448Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":115,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:35:41.0556704Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":158,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:40:45.0987698Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":158,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:45:49.1423110Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:50:53.1907622Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T21:55:54.2509271Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:00:58.3386130Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:06:02.4261381Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:11:06.5282019Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":117,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:16:10.6023639Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:21:14.6658839Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":117,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:26:18.7346677Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":117,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:31:22.7989256Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":117,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:36:26.8437615Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:41:30.9196263Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:46:34.9676957Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:51:39.0408505Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T22:56:43.1073602Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T23:01:47.1646238Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":36,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T23:06:51.2367168Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":212,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T23:11:55.2795091Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":212,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
{"@t":"2021-02-14T23:16:59.3552192Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":9980,"ProcessName":"iisexpress","ThreadId":212,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-V0D5VFJ","Log4NetLevel":"ERROR"}
